/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_relinc_processor_pico_PicoScope */

#ifndef _Included_net_relinc_processor_pico_PicoScope
#define _Included_net_relinc_processor_pico_PicoScope
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_relinc_processor_pico_PicoScope
 * Method:    ps5000OpenUnit
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_net_relinc_processor_pico_PicoScope_ps5000OpenUnit
  (JNIEnv *, jobject);

/*
 * Class:     net_relinc_processor_pico_PicoScope
 * Method:    ps5000CloseUnit
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_net_relinc_processor_pico_PicoScope_ps5000CloseUnit
  (JNIEnv *, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
